# Generated by Django 5.0.1 on 2024-01-29 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'To-Do',
                'verbose_name_plural': 'To',
            },
        ),
    ]
